cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true
blockExoticSubdeps: true
trustPolicy: 'no-downgrade'

packageExtensions:
  '@codspeed/vitest-plugin@*':
    peerDependenciesMeta:
      vite:
        optional: true

packages:
  - 'benchmarks/*'
  - 'packages/*'

allowBuilds:
  core-js: false
  esbuild: true
  nx: false
  unrs-resolver: false
